PATH_DATASETS = '/dataset/evaluation/'
PATH_RESIZED_DATASETS = "/dataset/pretraining/"
PATH_DATASETS_TRANSFERABILITY = "/dataset/evaluation/"

PATH_DATAFRAME_PRETRAIN = "./local_data/dataframes/pretraining/"
PATH_DATAFRAME_TRANSFERABILITY = "./local_data/dataframes/evaluation/"
PATH_DATAFRAME_TRANSFERABILITY_CLASSIFICATION = PATH_DATAFRAME_TRANSFERABILITY + "classification/"
PATH_DATAFRAME_TRANSFERABILITY_SEGMENTATION = PATH_DATAFRAME_TRANSFERABILITY + "segmentation/"

PATH_RESULTS_PRETRAIN = "./ckpt/"
PATH_RESULTS_TRANSFERABILITY = "./results/"
